### ISSUE TITLE
Slew epoch

### ISSUE THREAD

**Issue by wschoenell** [astroufsc/chimera-astelco#1]
Check if the bugfix on astroufsc/chimera#111 is fixed with this telescope. I think that you should add the line below at the beginning of `slewToRaDec()`.

``` python
position = position.toEpoch(Epoch.NOW)
```

**Comment by wschoenell** [comment]
Relates to astroufsc/chimera#114 too.

**Comment by tribeiro** [comment]
Fixed with #3.
